name: Deploy to Vercel

on:
  push:
    branches:
      - main # ou a branch que vocÃª deseja monitorar para deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: |
          curl -o- https://raw.githubusercontent.com/vercel/cli/$(curl -s https://api.github.com/repos/vercel/cli/releases/latest | jq -r .tag_name)/dist/bin/vercel.js | sudo tee /usr/local/bin/vercel > /dev/null
          sudo chmod +x /usr/local/bin/vercel

      - name: Deploy to Vercel
        run: vercel --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
